name: ADHD 앱 자동 배포

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v4
      
    - name: Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 의존성 설치
      run: |
        npm cache clean --force
        npm install --legacy-peer-deps      
    - name: React 앱 빌드
      run: |
        npm run build
      env:
        CI: false
        PUBLIC_URL: /charmleader-adhd2
        GENERATE_SOURCEMAP: false
        
    - name: Pages 설정
      uses: actions/configure-pages@v4
      
    - name: 빌드 아티팩트 업로드
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: GitHub Pages 배포
      id: deployment
      uses: actions/deploy-pages@v4